version: '2.2'

services:

  erigon:
    image: thorax/erigon:${TAG:-latest}
    build: .
    command: erigon ${ERIGON_FLAGS-} --datadir=/home/erigon/.local/share/erigon --private.api.addr=0.0.0.0:9090 --downloader.api.addr=downloader:9093 --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061
    volumes:
      # This is "datadir". It's ok to mount sub-dirs of "datadir" to different drives
      - ./erigon:/home/erigon/.local/share/erigon
    ports:
      - "31303:30303/tcp"
      - "31303:30303/udp"
      - "31304:30304/tcp"
      - "31304:30304/udp"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.32.1
    user: 1000:1000 # Uses erigon user from Dockerfile
    command: --log.level=warn --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    ports:
      - "9090:9090"
    volumes:
      - ./cmd/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./erigon-prometheus:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:8.3.4
    user: 1000:1000 # Uses erigon user from Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./cmd/prometheus/grafana.ini:/etc/grafana/grafana.ini
      - ./cmd/prometheus/datasources:/etc/grafana/provisioning/datasources
      - ./cmd/prometheus/dashboards:/etc/grafana/provisioning/dashboards
      - ./erigon-grafana:/var/lib/grafana
    restart: unless-stopped

  rpcdaemon: # Service to server JSON-RCP API
    image: thorax/erigon:${TAG:-latest}
    command: rpcdaemon ${RPCDAEMON_FLAGS-} --datadir=/home/erigon/.local/share/erigon --private.api.addr=erigon:9090 --txpool.api.addr=erigon:9090 --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --http.api=eth,debug,net --ws
    pid: service:erigon # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
    volumes_from:
      - erigon
    ports:
      - "8645:8545"
      - "8650:8550"
    restart: unless-stopped

  downloader: # Service to download/seed historical data
    image: thorax/erigon:${TAG:-latest}
    command: downloader ${DOWNLOADER_FLAGS-} --datadir=/home/erigon/.local/share/erigon --downloader.api.addr=0.0.0.0:9093
    pid: service:erigon # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
    #cpus: 0.2 # No real-time computation here, so - limit it hard
    volumes_from:
      - erigon
    ports:
      - "9093:9093"
      - "42069:42069"
    restart: unless-stopped