version: "3.6"
services:
  
  bitcoind:
    container_name: bitcoind
    hostname: bitcoind
    image: kylemanna/bitcoind
    ports:
      - "10083:8333"
    #   - "127.0.0.1:8332:8332"
      - "10082:8332"
    volumes:
      - "./data:/bitcoin/.bitcoin"
      - "./config/bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`venus.arz.team`)"
  #     - "traefik.http.routers.whoami.entrypoints=websecure"
  #     - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    restart: always

networks:
  default:
    external:
      name: vnet
