version: "3.8"

services:
  ethereum-geth:
    # image: ethereum/client-go:latest
    image: ethereum/client-go:v1.10.15
    volumes:
      - ./eth:/home/arz_eth/.ethereum:rw
      - ./eth:/home/arz_eth/:rw
    ports:
      - 30303:30303/tcp
      - 30304:30304/udp
      - 8546:8546
      - 8545:8545
    command:
      #     # Blockchain sync mode ("snap", "full" ,"light")
      - --syncmode=full
      #     # Megabytes of memory allocated to internal caching
      #     "--cache=8192",
      # Enable the HTTP-RPC server
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=eth,net,web3,txpool
      # Enable GraphQL on the HTTP-RPC server. Note that GraphQL can only be started if an HTTP server is started as well.
      - --graphql
      - --graphql.vhosts=*
      - --allow-insecure-unlock
      # Enable metrics collection and reporting
      - --metrics
      - --metrics.expensive
      - --pprof
      - --pprof.addr=0.0.0.0
      # Enable the WS-RPC server
      - --ws
      - --ws.addr=0.0.0.0
    #     # Enable metrics collection and reporting
    #     "--metrics",
        # Ethereum mainnet
      - --mainnet
    #     # --ipcdisable,
    #     # Maximum number of network peers (network disabled if set to 0) (default: 50)
    #     # "--maxpeers=30",
      # Data directory for the databases and keystore (default: "/root/.ethereum")
      - --datadir=/home/arz_eth/.ethereum
    healthcheck:
      test: ["CMD", "geth", "attach", "http://localhost:8545", "--exec", "eth.blockNumber"]
      interval: 10s
      retries: 10
