FROM python:3.9

WORKDIR /home/app

COPY requirements.txt /home/app

RUN python -m pip install -U pip \
    && pip install -r /home/app/requirements.txt && ls

COPY . /home/app/

CMD [ "python","transactions.py" ]

