version: '3.6'
services:
  postgres:
    image: postgres:latest
    hostname: psql
    restart: always
    ports:
      - "5432:5432"
    volumes:
    - /drive_data/unofficials/fastapi-auth/psql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1
  graphql-engine:
    image: hasura/graphql-engine:v2.1.1
    ports:
    - "8888:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:1@psql:5432/api
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://postgres:1@psql:5432/api
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey



