- ClusterId: 22
  Created: 1577880000000
  Description: ''
  Enabled: true
  MaxScore: 100
  MinScore: 100
  Modified: 1577880000000
  Module: device
  Name: os
  RequiredReview: false
  Rules:
    Rule1: false
    Rule2: true
  Type: NO_CODE
- ClusterId: 29
  Created: 1577880000000
  Description: rule with params test
  Enabled: true
  MaxScore: 100
  MinScore: 100
  Modified: 1577880000000
  Module: device
  Name: rule with params test
  ParametersRules:
  - DecisionType: all
    Features:
      feature1:
        op: '>'
        value: 10
      feature2:
        op: ==
        value: true
      feature3:
        op: range
        value:
        - 4
        - 10
      feature4:
        op: '!='
        value: None
  - DecisionType: any
    Features:
      feature5:
        op: <
        value: 1000
  RequiredReview: false
  Rules:
    Rule: false
  Type: NO_CODE
